export const ADD_STUDENT = 'ADD_STUDENT'; 
export const STUDENTS_LOADING = 'STUDENTS_LOADING';  
export const STDUENTS_FAILED = 'STDUENTS_FAILED';  
export const RENDER_STUDENTS = 'RENDER_STUDENTS';  